application: proyecto-als
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app

- url: /lines
  script: handlers.lines.list.app
  login: required

- url: /lines/new
  script: handlers.lines.new.app
  login: required

- url: /lines/delete
  script: handlers.lines.delete.app
  login: required

- url: /css
  static_dir: templates/css

- url: /scss
  static_dir: templates/scss

- url: /img
  static_dir: templates/img

- url: /vendor
  static_dir: templates/vendor


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
